### ISSUE TITLE
Error when running `examples/rat_hippocampus/run_marble_and_cebra.ipynb`

### ISSUE THREAD

**Issue by rodrigo-pena** [Dynamics-of-Neural-Systems-Lab/MARBLE#33]
Hi, I was trying to run the notebook `examples/rat_hippocampus/run_marble_and_cebra.ipynb` but ran into an error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 21
      9 params = {
     10     "epochs": 100,
     11     "order": 1,  # order of derivatives
   (...)
     17     "include_positions": True,
     18   }
     20 model = MARBLE.net(data, params=params.copy()) #define model
---> 21 model.fit(data, outdir=f"{HOME}[/data/hippocampus_{rat}") # train model
     22 data = model.transform(data) #evaluate model

File [~/miniconda3/envs/sfb/lib/python3.11/site-packages/MARBLE/main.py:361], in net.fit(self, data, outdir, verbose)
    358 self, data, _ = utils.move_to_gpu(self, data)
    360 # data loader
--> 361 train_loader, val_loader, test_loader = dataloader.loaders(data, self.params)
    362 optimizer = opt.SGD(
    363     self.parameters(), lr=self.params["lr"], momentum=self.params["momentum"]
    364 )
    365 if hasattr(self, "optimizer_state_dict"):

File [~/miniconda3/envs/sfb/lib/python3.11/site-packages/MARBLE/dataloader.py:18], in loaders(data, par)
      9 """Loaders."""
     10 nb = [par["n_sampled_nb"]] * par["order"]
     12 train_loader = NeighborSampler(
     13     data.edge_index,
     14     sizes=nb,
     15     batch_size=par["batch_size"],
     16     shuffle=True,
     17     num_nodes=data.num_nodes,
---> 18     node_idx=data.train_mask,
     19 )
     21 val_loader = NeighborSampler(
     22     data.edge_index,
     23     sizes=nb,
   (...)
     27     node_idx=data.val_mask,
     28 )
     30 test_loader = NeighborSampler(
     31     data.edge_index,
     32     sizes=nb,
   (...)
     36     node_idx=data.test_mask,
     37 )

File [~/miniconda3/envs/sfb/lib/python3.11/site-packages/torch_geometric/data/data.py:561], in Data.__getattr__(self, key)
    555 if '_store' not in self.__dict__:
    556     raise RuntimeError(
    557         "The 'data' object was created by an older version of PyG. "
    558         "If this error occurred while loading an already existing "
    559         "dataset, remove the 'processed' directory in the dataset's "
    560         "root folder and try again.")
--> 561 return getattr(self._store, key)

File [~/miniconda3/envs/sfb/lib/python3.11/site-packages/torch_geometric/data/storage.py:96], in BaseStorage.__getattr__(self, key)
     94     return self[key]
     95 except KeyError:
---> 96     raise AttributeError(
     97         f"'{self.__class__.__name__}' object has no attribute '{key}'"
     98     ) from None

AttributeError: 'GlobalStorage' object has no attribute 'train_mask'
```

**Comment by rodrigo-pena** [comment]
I can load the data and display the spike train:

![Image](https://github.com/user-attachments/assets/4f438e3d-ebe5-472f-bfdc-56dcca7eb914)

But run into the above error when running the cell in the section "Train MARBLE with only neural data"

**Comment by nanyicui** [comment]
I experience the same problem using the macaque reaching data. 
Windows platform, torch2.2.0+cu118

**Comment by agosztolai** [comment]
Hello, 

unfortunately, I could not reproduce your error. However, the 'train_mask' error is likely related to the version of torch and torch_geometric that you are using. I am using torch '1.12.1' and torch_geometric '2.1.0'. Could you please try with these versions? The provided environment [file](https://github.com/Dynamics-of-Neural-Systems-Lab/MARBLE/blob/main/environment_windows_native.yml) seems to already have the required versions.

Could you please install MARBLE using this environment file (for Windows or the equivalent file for other operating systems) and let me know if you still encounter the issue?

**Comment by rodrigo-pena** [comment]
Hi @agosztolai,

I have created a separate environment using the `.yml` files, as you've suggested and the notebooks are now running as expected. 

Before, I was trying to install MARBLE on a project of mine's existing environment having `torch==2.5.0` and `torch-geometric==2.6.1`. I wanted to use MARBLE as a dependency there, but I guess it does not work with `torch>1.13` and `torch_geometric>2.1`. I think if I want to use MARBLE in the future I'll have to isolate it in its own environment and make sure that I export data from other projects in a way that MARBLE can process.

Best, and thanks for the quick reply

**Comment by agosztolai** [comment]
I will look into whether we can upgrade the torch/PyG versions to a newer one. However, we must be careful to preserve the compatibility with other projects.

**Comment by sharmavaruns** [comment]
For the toy_examples/vanderpol.ipynb I found that even though I'm using newer versions of torch/torch_geometric, the following code allowed me to run things downstream and bypasses the `AttributeError: 'GlobalStorage' object has no attribute 'train_mask'`:

<img width="332" height="170" alt="Image" src="https://github.com/user-attachments/assets/e02af56b-e406-4727-8c14-0cfd2660afb7" />

```
######## CODE I'VE ADDED #########
from torch_geometric.transforms import RandomNodeSplit
rns = RandomNodeSplit()
data = rns(data)
######## CODE I'VE ADDED #########

params = {'epochs': 50, #optimisation epochs
       'hidden_channels': 32, #number of internal dimensions in MLP
       'out_channels': 5,
       'inner_product_features': False,
       'diffusion': False
      }

model = MARBLE.net(data, params=params)
model.fit(data, outdir='model_large')
```
